### ISSUE TITLE
jwt.sql脚本文件不全

### ISSUE THREAD

**Issue by java-ys** [zeng-xian-guo/springboot_jwt_token#2]
![image](https://user-images.githubusercontent.com/36307913/126732479-6ad6eb89-2c04-4a23-9ad3-b3eef00225c7.png)
您好，可以补全下脚本吗？

**Comment by zeng-xian-guo** [comment]
CREATE TABLE `sys_task` (
&nbsp;&nbsp;`id` bigint(20) NOT NULL AUTO_INCREMENT,
&nbsp;&nbsp;`job_name` varchar(255) DEFAULT NULL COMMENT&nbsp;'任务名',
&nbsp;&nbsp;`description` varchar(255) DEFAULT NULL COMMENT&nbsp;'任务描述',
&nbsp;&nbsp;`cron_expression` varchar(255) DEFAULT NULL COMMENT&nbsp;'cron表达式',
&nbsp;&nbsp;`bean_class` varchar(255) DEFAULT NULL COMMENT&nbsp;'任务执行时调用哪个类的方法 包名+类名',
&nbsp;&nbsp;`job_status` varchar(255) DEFAULT NULL COMMENT&nbsp;'任务状态',0:停止1:运行,
&nbsp;&nbsp;`job_group` varchar(255) DEFAULT NULL COMMENT&nbsp;'任务分组',
&nbsp;&nbsp;`create_user` varchar(64) DEFAULT NULL COMMENT&nbsp;'创建者',
&nbsp;&nbsp;`create_time` datetime DEFAULT NULL COMMENT&nbsp;'创建时间',
&nbsp;&nbsp;`update_user` varchar(64) DEFAULT NULL COMMENT&nbsp;'更新者',
&nbsp;&nbsp;`update_time` datetime DEFAULT NULL COMMENT&nbsp;'更新时间',
&nbsp;&nbsp;PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=32&nbsp;DEFAULT CHARSET=utf8;<br&gt;<br&gt;INSERT INTO `sys_task` VALUES ('1',&nbsp;'QuertzTask1',&nbsp;'Quertz定时器测试一',&nbsp;'0/10 * * * * ?',&nbsp;'com.example.demo.Quertz.TestQuertzTask',&nbsp;'1',&nbsp;'group',&nbsp;null,&nbsp;null,&nbsp;null,&nbsp;null);



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zeng-xian-guo/springboot_jwt_token"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 上午10:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zeng-xian-guo/springboot_jwt_token] jwt.sql脚本文件不全 (#2)





 

 您好，可以补全下脚本吗？
